### ISSUE TITLE
Add a page about unit testing with Testing Library

### ISSUE THREAD

**Issue by amnrzv** [preactjs/preact-www#594]
I think `@testing-library/preact` is the preferred choice for many for testing preact frontend code and with that in mind, it'd be nice to have a page dedicated on the website for that.

Currently, we have a page dedicated to unit testing with Enzyme which requires more work to set up and has some issues. We can start off with a page to explain the alternate way of unit testing with `@testing-library/preact`, and maybe start updating templates to use testing-library as well.

Is this a good idea? Are there any major benefits of using enzyme over testing-library that I might not be considering? Keen to hear some thoughts.

**Comment by marvinhagemeister** [comment]
+1 we'd love to have a dedicated page for testing library 👍

**Comment by amnrzv** [comment]
Excellent! I'll start this page and share something soon.

**Comment by robertknight** [comment]
> Are there any major benefits of using enzyme over testing-library that I might not be considering?

Enzyme allows you to query the React tree (including props and custom components) rather than just the DOM tree. This is useful for writing unit tests for a component (say `Parent`) that renders other components (`ComplexChild`) where you might want to check that the `Parent` renders the correct `ComplexChild` outputs but doesn't depend on implementation details of the `ComplexChild`.

testing-library on the other hand emphasises integration testing more - rendering a tree of components and querying/acting against the DOM, the idea to focus more on perceiving the UI and acting upon it as a user would. The [FAQ](https://testing-library.com/docs/react-testing-library/faq) makes the case for this. A significant upside is that the API surface is area is smaller and so there is less to learn.

As far as the Preact documentation goes, I think we probably don't want to confront less experienced developers with a non-trivial decision about testing philosophy if they are just trying to get started with the library and write their first test. So while both Enzyme and testing-library are widely used and there are valid reasons to choose both, IMO the docs ought to make a specific recommendation for newcomers. FWIW React recommends testing-library.

testing-library does have a [good section](https://testing-library.com/docs/preact-testing-library/intro) about Preact on its main website, so the preactjs.com docs could potentially link to that rather than repeating all of it, or maybe have a short example and then link to it for further reading.

In terms of overall organization of the testing pages, the React [Testing Overview](https://reactjs.org/docs/testing.html) docs are pretty good. They talk about the high-level types of tests that a developer might want to write, as well as the trade-offs involved with different types of tests / tools and then provide some specific recommendations for getting started as well as recipes for common needs.

**Comment by rschristian** [comment]
Was added in #654
